---
- hosts: dev
  gather_facts: no
  tasks:
    - name: create directory
      file:
           path: "/root/tmp/gameoflife"
           state: directory

    - name: copy the file
      copy: 
          src: "{{ work }}/gameoflife-0.0.1.war"
          dest: "/root/tmp/gameoflife/gameoflife.war"
          mode: 0777
          
    - name: deploy the gameoflife
      shell: "cd /root/tmp/gameoflife ; nohup java -jar gameoflife.war &"
